### ISSUE TITLE
Support Default Transformations in Cloudinary Media Library Widget 

### ISSUE THREAD

**Issue by Abd-Alwahab** [Kentico/kontent-custom-element-cloudinary#4]
The images should be received as formatted while using the media library widget of cloudinary, it should be modified via custom JSON parameters 

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/45470303/165953047-61f53683-aa9b-4d08-8b84-7c8d586161b8.png)

https://cloudinary.com/documentation/media_library_widget#sample_configuration_options_definition

**Comment by strizr** [comment]
the defaultTransformation config property has been added.
